### ISSUE TITLE
Release to PyPI via Github Action

### ISSUE THREAD

**Issue by MartinThoma** [camelot-dev/camelot#389]
As the maintainer of pypdf I've recently decided to add a Github Action that can make releases of pypdf to PyPI. See https://github.com/py-pdf/pypdf/blob/main/.github/workflows/release.yaml

# Reasons for adding a `workflows/release.yaml` Github Action

1. *Saving time*: Yes, releasing is just a `flit publish` in my case. But still an extra step.
2. *Reducing complexity*: Again, just one step was removed. But I'm happy if this becomes easier.
3. *Allowing the community to release*: pypdf was not active for a long time. It could happen again if I became inactive. While we have some people on Github in the py-pdf organization / the pypdf repository with e.g. the permission to merge, I didn't want to add people to the project as the permission system of PyPI is lacking (e.g. the new admins could remove myself as an admin - no chance to recover). However, you can create project-based tokens that have only the permission to publish new packages.

# How it works

## Requirements

1. Create a token: https://pypi.org/help/#apitoken
2. Go to https://github.com/camelot-dev/camelot/settings/secrets/actions and store it as a repository secret called `FLIT_PASSWORD`

## Triggering Workflows
I chose to use new git tags as the triggering mechanism:

```
on:
  push:
    tags:
      - '*.*.*'
```

See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow for alternatives

## The action

```
      - name: Install Flit
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Publish Package to PyPI🚀
        env:
          FLIT_USERNAME: '__token__'
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          flit publish
```

That would require a `pyproject.toml`.

You could for sure also use twine, but there I would need to check how passing the secrets works

# Discussion

Let me know what you think about it :-)
